name: sam
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.10.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albumentations==1.4.3
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - anyio==4.11.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blessed==1.25.0
      - boto3==1.41.0
      - botocore==1.41.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.0
      - crcmod==1.7
      - croniter==1.3.15
      - cryptography==46.0.3
      - cycler==0.12.1
      - dateutils==0.6.12
      - decorator==5.2.1
      - deepdiff==7.0.1
      - editor==1.6.6
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.88.0
      - filelock==3.14.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2023.12.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inquirer==3.4.1
      - ipdb==0.13.13
      - ipython==8.18.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning==2.0.1
      - lightning-cloud==0.5.70
      - lightning-utilities==0.15.2
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mat4py==0.6.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - parso==0.8.5
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - prettytable==3.16.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==1.10.24
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.6
      - pytz==2023.4
      - pyyaml==6.0.3
      - readchar==4.2.1
      - redis==7.0.1
      - regex==2025.11.3
      - requests==2.28.2
      - rich==13.4.2
      - runs==1.2.2
      - s3transfer==0.14.0
      - safetensors==0.7.0
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tokenizers==0.21.4
      - tomli==2.3.0
      - torch==2.1.2+cu121
      - torchaudio==2.1.2+cu121
      - torchmetrics==1.8.2
      - torchvision==0.16.2+cu121
      - tqdm==4.65.2
      - traitlets==5.14.3
      - transformers==4.50.3
      - triton==2.1.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - websocket-client==1.9.0
      - websockets==11.0.3
      - xmod==1.8.1
      - yapf==0.43.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/osim-mir/anaconda3/envs/sam
